import{S as d,a as f,i}from"./assets/vendor-Bub99LOP.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const l=document.querySelector(".result-gallery");let m=new d(".result-gallery a",{captionsData:"alt",captionDelay:250});function h(s){if(!s||s.length===0)return;const t=s.map(({largeImageURL:a,webformatURL:o,tags:e,likes:r,views:n,comments:u,downloads:p})=>`
        <li class="result-item">
            <a href="${a}" class="picture-link">
                <img src="${o}" alt="${e}" loading="lazy" class="item-image" />
            </a>
            <div class="picture-text">
                <p class="text"><span class="bold-text">Likes</span> ${r}</p>
                <p class="text"><span class="bold-text">Views</span> ${n}</p>
                <p class="text"><span class="bold-text">Comments</span> ${u}</p>
                <p class="text"><span class="bold-text">Downloads</span> ${p}</p>
            </div>
        </li>`).join("");l.insertAdjacentHTML("beforeend",t),m.refresh()}function g(){l.innerHTML=""}function y(s){const t=document.querySelector(".search-text");document.querySelector(".search-form").addEventListener("submit",o=>{o.preventDefault();const e=t.value.trim();e!==""&&s(e),t.value=""})}const x="55070456-620b3af2625ed4d2721553348";async function b(s){try{return(await f.get("https://pixabay.com/api/",{params:{key:x,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}})).data}catch(t){throw t}}const c=document.querySelector(".loading-text");y(async s=>{g(),c.classList.remove("is-hidden");try{const a=(await b(s)).hits;!a||a.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):h(a)}catch(t){i.error({title:"Error",message:"Something went wrong while connecting to the server. Please try again later!",position:"topRight"}),console.error(t)}finally{c.classList.add("is-hidden")}});
//# sourceMappingURL=index.js.map
