import{S as g,a as y,i as l}from"./assets/vendor-Bub99LOP.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();function L(t){const r=document.querySelector(".search-text");document.querySelector(".search-form").addEventListener("submit",a=>{a.preventDefault();const e=r.value.trim();e!==""&&t(e),r.value=""})}const u=document.querySelector(".result-gallery");let b=new g(".result-gallery a",{captionsData:"alt",captionDelay:250});function v(t){if(!t||t.length===0)return;const r=t.map(({largeImageURL:o,webformatURL:a,tags:e,likes:s,views:n,comments:m,downloads:f})=>`
        <li class="result-item">
            <a href="${o}" class="picture-link">
                <img src="${a}" alt="${e}" loading="lazy" class="item-image" />
            </a>
            <div class="picture-text">
                <p class="text"><span class="bold-text">Likes</span> ${s}</p>
                <p class="text"><span class="bold-text">Views</span> ${n}</p>
                <p class="text"><span class="bold-text">Comments</span> ${m}</p>
                <p class="text"><span class="bold-text">Downloads</span> ${f}</p>
            </div>
        </li>`).join("");u.insertAdjacentHTML("beforeend",r),b.refresh()}function x(){u.innerHTML=""}const w="55070456-620b3af2625ed4d2721553348";async function S(t,r=1){try{return(await y.get("https://pixabay.com/api/",{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:40}})).data}catch(o){throw o}}const d=document.querySelector(".loading-text"),i=document.querySelector(".load-more-button");let p="",c;async function h(){try{d.classList.remove("is-hidden"),i.classList.add("is-hidden");const t=await S(p,c),r=t.hits,o=t.totalHits;if(!r||r.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(r),o>c*40?i.classList.remove("is-hidden"):l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){l.error({title:"Error",message:"Something went wrong while connecting to the server. Please try again later!",position:"topRight"}),console.error(t)}finally{d.classList.add("is-hidden")}}L(async t=>{p=t,c=1,x(),i.classList.add("is-hidden"),d.classList.remove("is-hidden"),await h()});i.addEventListener("click",async()=>{c++,await h();const{height:t}=document.querySelector(".result-gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
